name: Trigger auto deployment for newscollectorservice

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/newscollectorservice-AutoDeployTrigger-2795d2a2-34eb-4360-a590-d1f3c34568b2.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NEWSCOLLECTORSERVICE_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.NEWSCOLLECTORSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.NEWSCOLLECTORSERVICE_REGISTRY_PASSWORD }}
          containerAppName: newscollectorservice
          resourceGroup: brandy.io_dev
          imageToBuild: soumitsr/newscollectorservice:${{ github.sha }}
          
            

     

